openapi: '3.0.3'
info:
  title: bttger/web-framework-benchmarks
  description: |
    ### This is the OpenAPI Definition of the [bttger/web-framework-benchmarks](https://github.com/bttger/web-framework-benchmarks) project to benchmark the overhead ⚙️ and latency ⏱️ of different popular web frameworks.
    It defines the interface which every web framework has to implement. The endpoints are chosen so that they cover the performance of the **routing**, **parsing** (of request parameters) and **serialization** (of responses) as distinctly as possible.
    
    This definition contains the mandatory response data in the description of properties.
  version: '0.1.0'
  license:
    name: MIT
    url: https://github.com/bttger/web-framework-benchmarks/blob/master/LICENSE
servers:
  - url: http://localhost:8080
paths:
  /serialize:
    get:
      operationId: getSerialized
      responses:
        "200":
          description: An object with a message property of the type string.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Hello, World!"
  /serialize/big:
    get:
      operationId: getSerializedBig
      responses:
        "200":
          description: An object covering all JSON types and being relatively large.
          content:
            application/json:
              schema:
                type: object
                properties:
                  family:
                    type: string
                    description: Elephantidae
                  scientificClassification:
                    type: object
                    properties:
                      kingdom:
                        type: string
                        description: Animalia
                      phylum:
                        type: string
                        description: Chordata
                      class:
                        type: string
                        description: Mammalia
                      order:
                        type: string
                        description: Proboscidea
                      superfamily:
                        type: string
                        description: Elephantoidea
                      classifier:
                        type: object
                        properties:
                          name:
                            type: string
                            description: John Edward Gray
                          born:
                            type: object
                            properties:
                              year:
                                type: integer
                                description: "1800"
                              month:
                                type: string
                                description: February
                              day:
                                type: integer
                                description: "12"
                              city:
                                type: string
                                description: Walsall
                              country:
                                type: string
                                description: England
                          died:
                            type: object
                            properties:
                              year:
                                type: integer
                                description: "1875"
                              month:
                                type: string
                                description: March
                              day:
                                type: integer
                                description: "7"
                              city:
                                type: string
                                description: London
                              country:
                                type: string
                                description: England
                          publications:
                            type: array
                            description: |
                              An array of 50 entries with publications of the classifier. Since we do not care about the content, we just generate
                              data with ascending year. The generation is solved on-demand and not with a pre-initialized object, to simulate the
                              language's performance losses when iterating through an (imaginary) database response.
                            items:
                              type: object
                              properties:
                                year:
                                  type: integer
                                  description: "1821"
                                related:
                                  type: boolean
                                  description: "true"
                                description:
                                  type: string
                                  description: Some discovery in 1821
  /plain/text:
    get:
      operationId: getPlainText
      responses:
        "200":
          description: Plain text outputting "Hello, World!"
          content:
            text/plain; charset=utf-8:
              example:
                "Hello, World!"
  /query/{userId}/tools/{offset}:
    get:
      operationId: getQueryResult
      description: The response has to confirm if an object with the queried properties is available.
      parameters:
        - name: userId
          in: path
          description: "300"
          required: true
          schema:
            type: integer
        - name: offset
          in: path
          description: "10"
          required: true
          schema:
            type: integer
        - name: x-api-key
          in: header
          description: zb478fb3
          required: true
          schema:
            type: string
        - name: x-session-id
          in: header
          description: jhg723bf
          required: true
          schema:
            type: string
        - name: model
          in: query
          description: Dozer
          required: true
          schema:
            type: string
        - name: factor
          in: query
          description: ATX
          required: true
          schema:
            type: string
        - name: length
          in: query
          description: "800"
          required: true
          schema:
            type: integer
        - name: width
          in: query
          description: "800"
          required: true
          schema:
            type: integer
        - name: allow
          in: query
          description: "true"
          required: true
          schema:
            type: boolean
      responses:
        "200":
          description: A confirmation object containing the corresponding id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "6000"
                  foundAt:
                    type: string
                    description: 2020-07-25T18:59:33.384Z (Current time in ISO 8601 UTC Format)
  /insert:
    post:
      operationId: insertObject
      description: Parses the transmitted object, serializes it with an additional id and creation timestamp and returns it.
      requestBody:
        description: An object containing all information to create a new object.
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Sample
                  addresses:
                    type: array
                    description: Two address items
                    items:
                      type: object
                      properties:
                        street:
                          type: string
                          description: Breite Straße
                        number:
                          type: integer
                          description: "292"
                        city:
                          type: string
                          description: Lübeck
                  oldTown:
                    type: boolean
                    description: "true"
              example:
                name: Sightseeing
                addresses:
                  - street: Breite Straße
                    number: 89
                    city: Lübeck
                  - street: Breite Straße
                    number: 89
                    city: Lübeck
                oldTown: true
      responses:
        "201":
          description: A confirmation object containing the created object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "300"
                  name:
                    type: string
                    description: Sample
                  addresses:
                    type: array
                    description: Two address items
                    items:
                      type: object
                      properties:
                        street:
                          type: string
                          description: Breite Straße
                        number:
                          type: integer
                          description: "292"
                        city:
                          type: string
                          description: Lübeck
                  oldTown:
                    type: boolean
                    description: "true"
                  createdAt:
                    type: string
                    description: 2020-07-25T18:59:33Z (Current time in ISO 8601 UTC Format)
